name: 'Python config generator prod'

on:
  push:
    branches:
      - 'main'

jobs:
  cfg_gen_prod:
    name: 'Config generator prod'
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout repository'
        uses: actions/checkout@v5

      - name: Main branch - Prod info
        run: echo "Lack of resources to build config generator PROD environment..."
